main_prompt_path_en: prompts/main_prompt_en.txt
main_prompt_path_zh: prompts/main_prompt_zh.txt
rag_summarize_prompt_path: prompts/rag_summarize.txt
classify_prompt_path: prompts/clothing_classification.txt