"""
Pydantic 請求/回應模型；對外可 `from app.schemas import ...`。
"""
from app.schemas.ai import (
    AIConversationCreate,
    AIConversationResponse,
    AIConversationUpdate,
    ChatReq,
)
from app.schemas.auth import (
    LoginResponse,
    PasswordChange,
    PasswordResetByIdentity,
    TokenData,
    TokenResponse,
    UserLogin,
)
from app.schemas.clothing import (
    BatchDeleteClothing,
    BatchUpdateClothing,
    ClothingAnalysis,
    ClothingCategory,
    ClothingCondition,
    ClothingFitType,
    ClothingItem,
    ClothingItemBase,
    ClothingItemCreate,
    ClothingItemList,
    ClothingItemUpdate,
    ClothingPattern,
    ClothingSeason,
    ClothingStats,
    ClothingTag,
    ClothingTagBase,
    ClothingTagCreate,
    ClothingTypeResponse,
    FilterOptions,
    SearchRequest,
    UploadResponse,
)
from app.schemas.common import ErrorResponse, ExportData, SuccessResponse
from app.schemas.model_photo import (
    ModelPhotoBase,
    ModelPhotoCreate,
    ModelPhotoInDB,
    ModelPhotoResponse,
    ModelPhotoUpdate,
)
from app.schemas.outfit import (
    Outfit,
    OutfitBase,
    OutfitCreate,
    OutfitItem,
    OutfitItemBase,
    OutfitItemCreate,
    OutfitUpdate,
)
from app.schemas.user import UserBase, UserCreate, UserResponse, UserUpdate
from app.schemas.virtual_tryon import (
    VirtualTryOnGenerateRequest,
    VirtualTryOnUploadFromStorageRequest,
)
from app.schemas.weather import WeatherLatLonParams
from app.schemas.wear_history import (
    CalendarOutfitItem,
    CalendarOutfitSave,
    WearHistory,
    WearHistoryBase,
    WearHistoryCreate,
)

__all__ = [
    "UserBase",
    "UserCreate",
    "UserResponse",
    "UserUpdate",
    "UserLogin",
    "PasswordResetByIdentity",
    "LoginResponse",
    "TokenData",
    "TokenResponse",
    "PasswordChange",
    "ClothingCategory",
    "ClothingSeason",
    "ClothingCondition",
    "ClothingFitType",
    "ClothingPattern",
    "ClothingTagBase",
    "ClothingTagCreate",
    "ClothingTag",
    "ClothingItemBase",
    "ClothingItemCreate",
    "ClothingItemUpdate",
    "ClothingItem",
    "ClothingItemList",
    "ClothingStats",
    "WearHistoryBase",
    "WearHistoryCreate",
    "WearHistory",
    "CalendarOutfitItem",
    "CalendarOutfitSave",
    "OutfitItemBase",
    "OutfitItemCreate",
    "OutfitItem",
    "OutfitBase",
    "OutfitCreate",
    "OutfitUpdate",
    "Outfit",
    "UploadResponse",
    "BatchUpdateClothing",
    "BatchDeleteClothing",
    "FilterOptions",
    "SearchRequest",
    "ClothingTypeResponse",
    "SuccessResponse",
    "ErrorResponse",
    "ClothingAnalysis",
    "ModelPhotoBase",
    "ModelPhotoCreate",
    "ModelPhotoUpdate",
    "ModelPhotoInDB",
    "ModelPhotoResponse",
    "ExportData",
    "ChatReq",
    "AIConversationCreate",
    "AIConversationUpdate",
    "AIConversationResponse",
    "VirtualTryOnGenerateRequest",
    "VirtualTryOnUploadFromStorageRequest",
    "WeatherLatLonParams",
]
